FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# DBIL

END POINT API Database to DynamoDB

## API Version
* /v1

## List All Content Category [/content/category]

**Endpoint Path:** `/content/category`

### Example [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Funny Videos",
                "description": "Only For Funny",
                "created_at": "2019-07-04T21:21:01+07:00",
                "id": "a8486ed6-59da-49c7-9605-466bef6dcd83",
                "updated_at": "2019-07-04T21:21:01+07:00"
            },
            {
                "name": "Funny Videos 223",
                "description": "Only For Funny 223",
                "created_at": "2019-07-04T21:27:23+07:00",
                "id": "cf31fb2e-9d06-49f9-af6f-c708edfe0871",
                "updated_at": "2019-07-04T22:13:07+07:00"
            }
        ]

## Create a New Content Category [/content/category/store]

**Endpoint Path:** `/content/category/store`

### Requests
| Parameter | type | Description |
| -- | --- | -- |
| `name` | string | name of content category |
| `description` | string | description of content category |

### Example [POST]
    
+ Request (application/json)

        {
           "name": "Action",
           "description": "Movie Action"
        }

+ Response 200 (application/json)

        {
            "status": {
                "code": "200",
                "message": "data has been saved"
            },
            "result": {
                "id": "bae04ac0-234a-431a-bed4-0bbc7026aa1c"
            }
        }
        
## Get Content Category by ID [/content/category/bae04ac0-234a-431a-bed4-0bbc7026aa1c]

**Endpoint Path:** `/content/category/{id}`

### Example [GET]

+ Response 200 (application/json)

        {
            "name": "Action",
            "description": "Movie Action",
            "created_at": "2019-07-05T09:47:05+07:00",
            "id": "bae04ac0-234a-431a-bed4-0bbc7026aa1c",
            "updated_at": "2019-07-05T09:47:05+07:00"
        }

## Search Content Category [/content/category/search]

**Endpoint Path:** `/content/category/search`

### Requests
| Parameter | type | Description |
| -- | --- | -- |
| `name` | string | name of content category |

### Example [POST]
    
+ Request (application/json)

        {
           "name": "Action",
        }

+ Response 200 (application/json)

        {
            "status": {
                "code": "200",
                "message": "search query has been performed, data has been found",
                "total": 2
            },
            "result": [
                {
                    "name": "Action",
                    "description": "Movie Action",
                    "created_at": "2019-07-05T09:47:05+07:00",
                    "id": "bae04ac0-234a-431a-bed4-0bbc7026aa1c",
                    "updated_at": "2019-07-05T09:47:05+07:00"
                },
                {
                    "name": "Action",
                    "description": "Movie Action",
                    "created_at": "2019-07-05T09:49:11+07:00",
                    "id": "8f245544-b4ac-468d-b291-7d10806b94d9",
                    "updated_at": "2019-07-05T09:49:11+07:00"
                }
            ]
        }